#!/bin/bash
# Made by Hiratechi

MYIP=`ifconfig eth0 | awk 'NR==2 {print $2}'`
MYIP2="s/xxxxxxxxx/$MYIP/g";

if [[ $USER != 'root' ]]; then
	echo "Oops! root privileges needed"
	echo "Type sudo su to proceed!"
	exit
fi
while :
do
	rm deb9hiratechi
	clear
	echo " "
	echo " "
	echo "=======================Debian 9======================="
	echo " "
	echo "     ~Welcome to Hiratechi's Debian 9 Autoscript~"
	echo " "
	echo "=======================Hiratechi======================"
	echo "=================== TEAM EPIPHANY ===================="
	echo "=================== Alice Schuberg ==================="
	echo "==================== ALICIZATION ====================="
	echo " "
	echo "To install this VPN service,"
	echo "choose your own VPS Provider first"
	echo "Other VPS Provider will be added here sooner!"
	echo ""
	echo "🔊 02-14-2019"
	echo "We added AMAZON, but still on beta phase"
	echo ""
	echo "    [ MENU ]"
	echo "1. Digital Ocean"
	echo "2. Linode"
	echo "3. VULTR"
	echo "4. Cloudsigma"
	echo "5. Z.COM"
	echo "6. Amazon"
	echo "7. Google Cloud"
	echo "8. Exit"
	read -p "Choose from 1 to 8 : " option2
	case $option2 in
		1)
		clear
		echo "		[ DIGITAL OCEAN ]"
		echo ""
		echo "Starting to install..."
		echo ""
		echo "⚠️ Automatically cancelled if wrong"
		echo "VPS Provider has been chosen"
		sleep 2
		wget -O deb9hiratechi https://raw.githubusercontent.com/Hira20/VPSauto/master/do && chmod +x deb9hiratechi && ./deb9hiratechi
		;;
		2)
		clear
		echo "		[ LINODE ]"
		echo ""
		echo "Starting to install..."
		echo ""
		echo "⚠️ Automatically cancelled if wrong"
		echo "VPS Provider has been chosen"
		sleep 2
		wget -O deb9hiratechi https://raw.githubusercontent.com/Hira20/VPSauto/master/linode && chmod +x deb9hiratechi && ./deb9hiratechi
		;;
		3)
		clear
		echo "		[ VULTR ]"
		echo ""
		echo "Starting to install..."
		echo ""
		echo "⚠️ Automatically cancelled if wrong"
		echo "VPS Provider has been chosen"
		sleep 2
		wget -O deb9hiratechi https://raw.githubusercontent.com/Hira20/VPSauto/master/vultr && chmod +x deb9hiratechi && ./deb9hiratechi
		;;
		4)
		clear
		echo "		[ CLOUDSIGMA ]"
		echo ""
		echo "Not Available Yet"
		sleep 5
		;;
		5)
		clear
		echo "		[ Z.COM ]"
		echo ""
		echo "Not Available Yet"
		sleep 5
		;;
		6)
		clear
		echo "		[ AMAZON ]"
		echo ""
		echo "Starting to install..."
		echo ""
		echo "⚠️ Automatically cancelled if wrong"
		echo "VPS Provider has been chosen"
		sleep 2
		wget -O deb9hiratechi https://raw.githubusercontent.com/Hira20/VPSauto/master/amazon && chmod +x deb9hiratechi && ./deb9hiratechi
		;;
		7)
		clear
		echo "		[ GOOGLE CLOUD ]"
		echo ""
		echo "Not Available Yet"
		sleep 5
		;;
		8)
		clear
		echo "Installation was cancelled"
		sleep 5
		exit
		;;
	esac
done
cd
